### ISSUE TITLE
Add link to f-droid

### ISSUE THREAD

**Issue by 4mohamedaliii** [muslimpack/Qadaa#2]
Add link to download the app from F-droid in the readme.md

**Comment by HasanEltantawy** [comment]
We'll work on that in future Insha'Allah.

**Comment by IzzySoft** [comment]
@HasanEltantawy your Readme still links to my repo, while your app has a newer release at F-Droid which is not linked to. I'd usually remove the app from my repo at this point, but as you didn't replace the badge this would confuse those using your app. So may I kindly ask to adjust this (i.e. replace badge+link of my repo with the one from F-Droid)? Thanks in advance!

**Comment by HasanEltantawy** [comment]
@IzzySoft Is there a cretin way to make this?

**Comment by IzzySoft** [comment]
To make what: replacing the badge?

**Comment by HasanEltantawy** [comment]
@IzzySoft Can you provide me the link of the badge
and I can't find my app on f-droid to add the link to my repo

**Comment by IzzySoft** [comment]
Ah, that – yes, give me a moment… Link to F-Droid is easy: `https://f-droid.org/packages/<applicationId>/` (replace `<applicationId>` with the ID / package name of your app. And the badges can be found in the [artwork repo](https://gitlab.com/fdroid/artwork), you can find [instructions here](https://gitlab.com/fdroid/artwork/-/blob/master/badge/README.md).

**Comment by HasanEltantawy** [comment]
@IzzySoft I have added the badge and I'll wait to see my app on the site soon.

**Comment by IzzySoft** [comment]
@HasanEltantawy that requires your input on the RFP, as pointed out. It's stuck at waiting for your reply. So adding the F-Droid badge now was premature (apologies I didn't check in advance, I was just going by the suggestion of @4mohamedaliii which made me think it already is listed, and your response to it which seemed to confirm that).

So can you please answer [this post](https://gitlab.com/fdroid/rfp/-/issues/2123#note_1209301117) so that issue can be picked up again?
